### ISSUE TITLE
Search Hidden Items

### ISSUE THREAD

**Issue by DracoClaw** [mr-miner1/better-settings#12]
When searching settings, you should still be able to search for hidden items. I don't want my list bloated with every plugin, but sometimes I still need to adjust one of them.

**Comment by mr-miner1** [comment]
ig i could add that as a toggle but u can access them by typing "$hidden" in the search field

**Comment by DracoClaw** [comment]
I tried that, it doesnt seem to work

https://micro.sylo.digital/f/F8sm2f

**Comment by mr-miner1** [comment]
added in recent update
here's a preview:

https://user-images.githubusercontent.com/83544549/161035219-d23c7c59-7a2e-40fd-8b09-0ee9d00a9eb8.mp4
