### ISSUE TITLE
CRASHES ON RIGHT CLICKING "Discord Nitro" option

### ISSUE THREAD

**Issue by SheepCommander** [mr-miner1/better-settings#18]
I've right clicked on everything else, only Discord Nitro causes crash. I would've liked to hide Discord Nitro if possible.

***

Some unrelated feedback I wanted to add since I don't know where it's supposed to go
- Would hiding entire categories be possible? Or even better collapsible categories would be a godsent
- The sometimes randomly snapping up and down upon right clicking is annoying
- The delete plugin button is super finnicky in my experience (and also doesn't update, although that might just be a powercord thing in general)
- Trying to hide HypeSquad through GUI didn't work for some reason, it kept hiding Experiments and Developer Options but not HypeSquad. Ended up manually typing HYPESQUAD into hide options and it worked

**Comment by mr-miner1** [comment]
> I've right clicked on everything else, only Discord Nitro causes crash. I would've liked to hide Discord Nitro if possible.

ill look into it
> Would hiding entire categories be possible? Or even better collapsible categories would be a godsent

someday maybe? probably not anytime soon though
> The delete plugin button is super finnicky in my experience

i agree the current system is pretty terrible - i will probably add a modal to confirm deletion instead of the weird double click thing
> Trying to hide HypeSquad through GUI didn't work for some reason

will look into this too

**Comment by SheepCommander** [comment]
Thanks! BTW how would I update a plugin (or do they autoupdate)

**Comment by mr-miner1** [comment]
they auto update if you have the "update automatically in the background" setting enabled in User Settings > Powercord > Updater, if disabled you would get a notification when there is a pending update and then you can click 1 button to update manually

**Comment by SheepCommander** [comment]
ahhh thanks

**Comment by mr-miner1** [comment]
fixed the discord nitro crash bug and the hypesquad bug too

**Comment by SheepCommander** [comment]
Yoooo I just saw the notification to update in betterdiscord, thanks

**Comment by mr-miner1** [comment]
> The delete plugin button is super finnicky in my experience

https://user-images.githubusercontent.com/83544549/152113591-d8245f81-090e-4d06-924d-fbd9fbe9d54f.mp4

next update™ :)

**Comment by SheepCommander** [comment]
amazing
