### ISSUE TITLE
Plugin Settings button doesn't work

### ISSUE THREAD

**Issue by SheepCommander** [mr-miner1/better-settings#19]
The settings button on plugin cards does not show up.

Also for some reason I was having issues with hiding the Discord Houses, but after a few seconds it did work (not sure why it took longer to hide than all the other settings I'd hidden at the same time) and also for a while it wasn't letting me flick on/off the `Quick Actions` > `Settings` option

**Comment by mr-miner1** [comment]
https://user-images.githubusercontent.com/83544549/144653271-8643ee85-5ff3-4b96-9a35-42308f86d58f.mp4

works fine for me?

**Comment by SheepCommander** [comment]
WTF you're right it does now, maybe it fixed after I restarted my computer
