### ISSUE TITLE
[Bug] Settings pages do not work when the plugin is loaded.

### ISSUE THREAD

**Issue by CorellanStoma** [mr-miner1/better-settings#21]
Hello, all settings pages do not open when the plugin is loaded, which I think affects the latest canary version.

![image](https://user-images.githubusercontent.com/58918358/148473384-13fc88a8-1708-4d19-a051-21fb8791d473.png)

**Comment by mr-miner1** [comment]
Hi, I'm not sure what you mean could you elaborate?

**Comment by DracoClaw** [comment]
After the latest powercord update, when this plugin is loaded, it's not possible to open user/guild/channel settings.

**Comment by mr-miner1** [comment]
works fine for me :/ do you get an error in the console?

**Comment by mr-miner1** [comment]
update: the issue was with recent and infamous canary update
will be fixed by the end of the week

**Comment by SheepCommander** [comment]
Yooo Imma test rn

**Comment by SheepCommander** [comment]
Can confirm it fully functions now, thank you
