### ISSUE TITLE
Separate Plugins category not working

### ISSUE THREAD

**Issue by SheepCommander** [mr-miner1/better-settings#22]
![image](https://user-images.githubusercontent.com/66646514/149249232-5c31d60e-d142-40ea-803e-68d423fc1829.png)

**Comment by mr-miner1** [comment]
i am aware of the bug but i am not at home right now I'll try and fix it next week though

**Comment by mr-miner1** [comment]
the issue seems to have fixed itself for me.
is it fixed you guys too?
@SheepCommander @vojta-dev

**Comment by vojta-dev** [comment]
Yeah, after updating to 1.6, it's fixed 🎉

**Comment by mr-miner1** [comment]
nice, but since it broke itself for me again and I didn't actually do anything to fix it, I'm probably gonna just have to redo how it works in the next update.

**Comment by mr-miner1** [comment]
should actually work now
if it doesn't I will cry
