### ISSUE TITLE
This plugin has some visual problems with light mode.

### ISSUE THREAD

**Issue by ivan123-tty** [mr-miner1/better-settings#24]
![image](https://user-images.githubusercontent.com/70339505/156070877-c21d0c67-219e-445c-b056-14fe61f31d3c.png)
![image](https://user-images.githubusercontent.com/70339505/156070889-4743cdf4-d830-40cf-87c8-a1b9128410be.png)

**Comment by mr-miner1** [comment]
ah. my bad for hardcoding those values ill change them to use the normal text color
